### ISSUE TITLE
Empty requirements and strange issue.

### ISSUE THREAD

**Issue by Possibly-Matt** [Tails578/SheRaFirstOnesTranslations#1]
Hi! Seems like the requirements.txt is empty but thats okay because you can just pip install flask.

But I'm also getting another issue as shown.
![image](https://user-images.githubusercontent.com/12588174/87811770-1350e500-c857-11ea-8a19-f2afa462e624.png)
I'm not sure if I'm doing anything wrong but all I'm doing is 
`python Main.py`

Thanks !

**Comment by Possibly-Matt** [comment]
Sorry! Just realized this is exactly what was intended. I am struggling to find the delete issue button...

**Comment by Tails578** [comment]
No worries.  I just saw your issue in my inbox.  The three lines from the photo is the intended home page at the moment.  I'll add a better description so incoming users know that their server is working correctly.  Right now, the focus is on rendering the symbols with WebGL, so the UI will be done after that.

**Comment by Possibly-Matt** [comment]
Ah okay, good to know. If you have a To-do list please add it ! Thanks for the reply.
